---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: json-crack
  name: json-crack
---
apiVersion: v1
kind: Service
metadata:
  name: json-crack-client-service
  namespace: json-crack
  labels:
    service: json-crack-client
spec:
  type: NodePort
  selector:
    service: json-crack-client
  ports:
    - port: 8888
      nodePort: 30444
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: json-crack-client-deployment
  namespace: json-crack
  labels:
    service: json-crack-client
spec:
  replicas: 1
  selector:
    matchLabels:
      service: json-crack-client
  template:
    metadata:
      labels:
        service: json-crack-client
    spec:
      hostAliases:
      - ip: "192.168.0.10"
        hostnames:
        - "rehl-k8s-server"
      containers:
      - name: json-crack-client-pod
        image: pull.$(hostname --fqdn):30443/smallworld-docker/json-crack:v2.0.0
      imagePullSecrets:
      - name: regsecret
